Added check for python version
nod-ai/SHARK pull request #1570
Opened 2023-06-21 21:51 UTC by Ranvirsv

2023-06-21 21:54 UTC, powderluv requested changes

2023-06-21 21:54 UTC, powderluv commented on setup_venv.sh
> +if [[ "$(python3 --version 2>&1)" != "Python 3.11"* ]]; then
like below `if [ "$PYTHON_VERSION_X_Y" == "3.11" ]; then`

2023-06-21 21:55 UTC, Ranvirsv commented on setup_venv.sh
> +if [[ "$(python3 --version 2>&1)" != "Python 3.11"* ]]; then
Oh okay

2023-06-22 00:51 UTC, powderluv approved these changes

2023-06-22 01:56 UTC, merged