added functionality for int8 vicuna and 4 shards
nod-ai/SHARK pull request #1712
Opened 2023-08-03 19:10 UTC by Eliasj42

2023-08-03 19:15 UTC, powderluv commented
lilnt please

2023-08-03 19:20 UTC, Eliasj42 commented
> lilnt please

added

2023-08-03 19:24 UTC, dan-garvey requested changes

2023-08-03 19:24 UTC, dan-garvey commented on apps/language_models/scripts/vicuna_4_shards.py
Lets try and avoid adding this file altogether. Most of this is just copied from elsewhere or is specific to the 4_shards setup. Lets make a 4 shards model wrapper file or something similar under src, and then use the single vicuna.py script as an entry point

2023-08-03 19:24 UTC, dan-garvey commented on apps/language_models/src/model_wrappers/vicuna_sharded_model.py
> +        # assert len(layers) == len(model.model.layers)
dead code?

2023-08-03 19:24 UTC, dan-garvey commented on apps/language_models/scripts/chatbot.py
was there a reason you wanted to keep it separate?

2023-08-03 22:30 UTC, dan-garvey requested changes

2023-08-03 22:30 UTC, dan-garvey commented on apps/language_models/scripts/vicuna_4_shards.py
Even if it takes more time and we can't merge it by tomorrow, I still think its better to remove this and leave vicuna.py as the single main function for vicuna models.

2023-08-03 22:30 UTC, dan-garvey commented on apps/stable_diffusion/web/ui/stablelm_ui.py
> +                ShardedVicuna as UnshardedVicuna,
nice

2023-08-03 22:30 UTC, dan-garvey commented on apps/stable_diffusion/web/ui/stablelm_ui.py
> +                ShardedVicuna as UnshardedVicuna,
but please change all mentions of unsharded vicuna to "as Vicuna". This will make it less confusing for anyone to read later

2023-08-04 19:04 UTC, dan-garvey approved these changes

2023-08-04 19:05 UTC, merged