Bandaid fix 2
nod-ai/SHARK pull request #1728
Opened 2023-08-05 00:10 UTC by Eliasj42

2023-08-07 17:01 UTC, dan-garvey requested changes

2023-08-07 17:05 UTC, Eliasj42 commented on apps/language_models/scripts/vicuna.py
> +                "--iree-codegen-linalg-max-constant-fold-elements=9223372036854775807"
Anush told me to add those tags to get it to run.  I think he and Stella understand them better than me

2023-08-08 03:38 UTC, stellaraccident commented on apps/language_models/scripts/vicuna.py
> +                "--iree-codegen-linalg-max-constant-fold-elements=9223372036854775807"
It is just int64_max, which was the old default value for that flag before I charged it to 0.

2023-08-08 03:39 UTC, stellaraccident commented on apps/language_models/scripts/vicuna.py
> +                "--iree-codegen-linalg-max-constant-fold-elements=9223372036854775807"
If we're going to keep this flag for long, we should make it more ergonomic

2023-08-08 17:14 UTC, dan-garvey approved these changes

2023-08-08 17:14 UTC, merged