Added ZoeDepth Support to SHARK
nod-ai/SHARK pull request #1741
Opened 2023-08-09 01:15 UTC by AyaanShah2204

```
python apps/stable_diffusion/scripts/img2img.py  --precision=fp16 --device=vulkan --prompt="barbie pink dog" --max_length=64 --import_mlir iree-hal-dump-executable-sources --enable_stack_trace --no-use_tuned  --img_path=C:\Users\nithin\intern_stuff\SHARK\wolf.jpg --use_stencil="zoedepth"
```
This will use the stable diffusion stencil pipeline to create a depth map of the input image and then stay faithful to the depth map when generating new images.

2023-08-09 01:27 UTC, powderluv requested changes

2023-08-09 01:27 UTC, powderluv commented on apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
> +
white space

2023-08-09 01:38 UTC, AyaanShah2204 commented on apps/stable_diffusion/src/pipelines/pipeline_shark_stable_diffusion_stencil.py
> +
done

2023-08-09 01:40 UTC, AyaanShah2204 commented
Changing to WIP. Looks like gitignore prevents `models` directory within zoe from being added. checking if I can move all the references to the `models` module into a utils file

2023-11-09 16:56 UTC, monorimet commented
Commit 72e27c96fce932b5b31f708af19a67d59a53d438 adds this support. Closing this PR.

2023-11-09 16:56 UTC, closed without merging