Code refactoring
nod-ai/SHARK pull request #1817
Opened 2023-09-05 07:07 UTC by tosemml

These slight code adjustments aim to enhance Pythonic quality by incorporating python `str.join`

2023-09-07 16:14 UTC, monorimet requested changes
Can't we remove `res = f"[{res[:-2]}]"` and just use `res = ", ".join(ext_list)` ? seems like we add and remove a comma at the end which doesn't need to happen anymore.

2023-09-11 16:28 UTC, dan-garvey approved these changes

2023-09-11 16:28 UTC, dan-garvey commented
Looks good to me. Test failure seems unrelated

2023-09-11 16:30 UTC, monorimet approved these changes
LGTM

2023-09-11 16:30 UTC, merged