enable additional flags for tank test models
nod-ai/SHARK pull request #866
Opened 2023-01-24 22:00 UTC by aldesilv

enabled im2col and winograd flags

2023-01-30 21:40 UTC, monorimet commented
This is great, thank you -- I'm doing a rebase that should fix the CI issue encountered here previously.

2023-01-30 21:41 UTC, monorimet approved these changes
LGTM!

2023-01-31 00:10 UTC, powderluv commented
can we rebase / land this ?

2023-01-31 00:24 UTC, monorimet requested changes
See comments

2023-01-31 00:24 UTC, monorimet commented on tank/all_models.csv
> +squeezenet1_0,linalg,torch,1e-2,1e-3,default,nhcw-nhwc/img2col,False,False,True,"https://github.com/nod-ai/SHARK/issues/388"
We should remove img2col here if it's currently broken (see CI) and merge :+1:

2023-02-02 00:36 UTC, powderluv commented
can we land this

2023-02-02 19:19 UTC, merged